# Generated by Django 3.0.5 on 2020-05-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportsmen', models.CharField(max_length=255)),
                ('distance', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('place', models.IntegerField()),
                ('track', models.IntegerField()),
                ('number', models.IntegerField()),
                ('result_time', models.DateTimeField()),
            ],
        ),
    ]
