# Generated by Django 3.0.5 on 2020-05-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='place',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='result_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='sportsmen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='track',
            field=models.IntegerField(null=True),
        ),
    ]
