# Generated by Django 3.0.5 on 2020-05-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200528_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='number',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='place',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='result_time',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='sportsmen',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='time',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='track',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
